[package]
description = "Copyable AWS resource IDs"
edition = "2021"
license = "MIT"
name = "aws-resource-id"
repository = "https://github.com/imbolc/aws-resource-id"
version = "0.1.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.7", features = ["postgres"] }
thiserror = "1"

[dev-dependencies]
serde_json = "1"
